# Author: crifan
# Date: 2012-05-16
#
# -----------------------------------------------------------------
#  generate output from DocBook sources
#  this is entry makefile for docbook
# -----------------------------------------------------------------
# run this makefile under src directory:
# [office]
# pwd = /home/CLi/develop/docbook/books/xxx/src
# [home]
# pwd = /cygdrive/e/Dev_Root/docbook/dev/books/xxx/src

################################################################################
# Project Settings
################################################################################

# also means main source file name
PROJECT_NAME = lan_coding_rule
SUB_SRC_FILES = \
	preface.xml \
	ch01_what_and_why_coding_rule.xml \
	ch02_common_coding_rule.xml \
	ch03_c_coding_rule.xml \
	ch04_cpp_coding_rule.xml \
	ch05_python_coding_rule.xml \
	ch06_go_coding_rule.xml \
	ch07_java_coding_rule.xml \
	ch08_csharp_coding_rule.xml \
	ch09_php_coding_rule.xml \
	ch10_js_coding_rule.xml \
	ch11_other_coding_rule.xml \
	reference.xml

DOCBOOK_MAKEFILE_ROOT = ../../../config
################################################################################
# Include docbook makefile
################################################################################
include $(DOCBOOK_MAKEFILE_ROOT)/docbook.mk